# basic options
title: Of Note
author: Madhuri Koushik
email: madhuri2k@gmail.com
description: This is a collection of notable items - solutions, references, step-by-step tutorials and demos. This is both a catalog or portfolio as well as a library for me to stash things worth remembering.
# twitter_username: 
github_username:  madhuri2k

# Build settings
markdown: kramdown
theme: minima
